# Generated by Django 6.0.5 on 2026-05-15 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('symbol', models.CharField(default='BTC', max_length=10)),
                ('stop_loss_pct', models.DecimalField(decimal_places=2, default=0.02, max_digits=5)),
                ('take_profit_pct', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('trade_amount_usdt', models.DecimalField(decimal_places=2, default=100.0, max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trade_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
