"""
Django settings for BinanceXchange project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.contrib import staticfiles
import os
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


def _database_url():
    url = os.environ.get('DATABASE_URL')
    if url:
        return url
    name = os.environ.get('DJANGO_DB_NAME')
    user = os.environ.get('DJANGO_DB_USER')
    password = os.environ.get('DJANGO_DB_PASSWORD')
    if name and user and password is not None:
        host = os.environ.get('DJANGO_DB_HOST', 'localhost')
        port = os.environ.get('DJANGO_DB_PORT', '5432')
        return f'postgresql://{user}:{password}@{host}:{port}/{name}'
    return f'sqlite:///{BASE_DIR / "db.sqlite3"}'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-change-me-for-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

_LOCAL_ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'web', '[::1]']
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=_LOCAL_ALLOWED_HOSTS)
if DEBUG:
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + _LOCAL_ALLOWED_HOSTS))

_LOCAL_CSRF_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://0.0.0.0:8000',
]
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=_LOCAL_CSRF_ORIGINS)
if DEBUG:
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS + _LOCAL_CSRF_ORIGINS))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
    'wallet',
    'binance_register',
    'Order',
    'edit_profile',
    'support',
    'referral',
    'qr_code',
    'autotrading',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BinanceXchange.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BinanceXchange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=_database_url(),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Optional for development:
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR]


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = env('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
OPEN_API = env('OPEN_API', default='')
COINGECKO_API_KEY = env('COINGECKO_API_KEY', default=None)

# Auto-trading bot (management command: python manage.py run_autotrading)
AUTO_TRADING = {
    'enabled': env.bool('AUTO_TRADING_ENABLED', default=False),
    'username': env('AUTO_TRADING_USERNAME', default=None),
    'pairs': ['BTC', 'ETH', 'BNB', 'SOL', 'XRP', 'AVAX', 'ADA', 'MATIC', 'DOT'],
    'position_size_usdt': env.float('AUTO_TRADING_POSITION_USDT', default=100),
    'buy_threshold': 1.005,
    'buy_return_threshold': env.float('AUTO_TRADING_BUY_RETURN', default=0.003),
    'sell_return_threshold': env.float('AUTO_TRADING_SELL_RETURN', default=-0.003),
    'min_usdt_for_buy': 10,
    'stop_loss_pct': env.float('AUTO_TRADING_STOP_LOSS_PCT', default=0.02),
    'take_profit_pct': env.float('AUTO_TRADING_TAKE_PROFIT_PCT', default=0.05),
    'sequence_length': 60,
    'gate_enabled': env.bool('AUTO_TRADING_GATE_ENABLED', default=False),
    'gate_min_r2': env.float('AUTO_TRADING_GATE_MIN_R2', default=0.0),
    'gate_min_directional_acc': env.float('AUTO_TRADING_GATE_MIN_DIR_ACC', default=51.5),
    'gate_max_mape': env.float('AUTO_TRADING_GATE_MAX_MAPE', default=15.0),
    'gate_require_log_return': True,
    'signal_centering': env.bool('AUTO_TRADING_SIGNAL_CENTERING', default=True),
}