# Generated by Django 5.2.1 on 2025-05-22 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='referral',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReferralReward',
        ),
    ]
