# Generated by Django 4.2.11 on 2024-05-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralreward',
            name='user',
        ),
    ]
