# Generated by Django 5.2.1 on 2025-05-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Чоловік'), (2, 'Жінка'), (3, 'Інше')], null=True),
        ),
    ]
