# Generated by Django 4.2.11 on 2024-03-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('btc', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('eth', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('usdt', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('bnb', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('sol', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('xrp', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('avax', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ada', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('matic', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('dot', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('currency', models.CharField(max_length=10)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_wallet', to='wallet.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_wallet', to='wallet.wallet')),
            ],
        ),
    ]
