# Generated by Django 5.0.2 on 2024-03-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('high_24h', models.FloatField(blank=True, null=True)),
                ('low_24h', models.FloatField(blank=True, null=True)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('total_supply', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=1600, null=True)),
                ('circulating_supply', models.CharField(blank=True, max_length=1600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cryptocurrency')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
